{application,bbb_test,
             [{applications,[kernel,stdlib,elixir,logger,nerves_runtime,
                             custom_bbb]},
              {description,"bbb_test"},
              {modules,['Elixir.BbbTest','Elixir.BbbTest.Application']},
              {registered,[]},
              {vsn,"0.1.0"},
              {mod,{'Elixir.BbbTest.Application',[]}},
              {extra_applications,[logger]}]}.
